# Generated by Django 4.0.2 on 2022-03-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('lable', models.TextField(max_length=100, null=True)),
                ('transactionDate', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myledger.mygroup')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, null=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myledger.mygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='mygroup',
            name='members',
            field=models.ManyToManyField(through='myledger.Tally', to=settings.AUTH_USER_MODEL),
        ),
    ]
